replicaCount: 1

image:
  repository: ghcr.io/shreyaskn72/hello-world-flask-kubernets
  tag: master-0781209
  pullPolicy: Always

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  CELERY_BROKER_URL:
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: CELERY_BROKER_URL
  CELERY_RESULT_BACKEND:
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: CELERY_RESULT_BACKEND
  DB_HOST:
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: DB_HOST
  DB_USER:
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_USER
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_PASSWORD
  DB_NAME:
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: DB_NAME

rabbitmq:
  user: rabbituser
  password: rabbitpass

nodeSelector: {}

tolerations: []

affinity: {}

