apiVersion: v1
kind: Service
metadata:
  name: celery-beat
spec:
  type: ClusterIP
  selector:
    app: celery-beat
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
      name: metrics

