apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery-worker.fullname" . | default "celery-worker" }}
  labels:
    app: celery-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command:
            [
              "celery",
              "-A",
              "celery_app.celery",
              "worker",
              "--loglevel=info",
              "--pidfile=/tmp/celeryworker.pid",
              "--concurrency={{ .Values.worker.concurrency }}",
              "--max-tasks-per-child={{ .Values.worker.maxTasksPerChild }}",
              "--pool={{ .Values.worker.pool }}"
            ]
          env:
            - name: CELERY_BROKER_URL
              {{- toYaml .Values.env.CELERY_BROKER_URL | nindent 14 }}
            - name: CELERY_RESULT_BACKEND
              {{- toYaml .Values.env.CELERY_RESULT_BACKEND | nindent 14 }}
            - name: DB_HOST
              {{- toYaml .Values.env.DB_HOST | nindent 14 }}
            - name: DB_USER
              {{- toYaml .Values.env.DB_USER | nindent 14 }}
            - name: DB_PASSWORD
              {{- toYaml .Values.env.DB_PASSWORD | nindent 14 }}
            - name: DB_NAME
              {{- toYaml .Values.env.DB_NAME | nindent 14 }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - test -f /tmp/celeryworker.pid

            initialDelaySeconds: 30
            periodSeconds: 30

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - test -f /tmp/celeryworker.pid

            initialDelaySeconds: 15
            periodSeconds: 30
      restartPolicy: Always
