replicaCount: 1

image:
  repository: ghcr.io/shreyaskn72/hello-world-flask-kubernets
  tag: master-a70bc46
  pullPolicy: Always

service:
  type: NodePort
  nodePort: 30555

env:
  BROKER_URL: "amqp://rabbituser:rabbitpass@rabbitmq.messaging.svc.cluster.local:5672//"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

