apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flower.fullname" . | default "flower" }}
  labels:
    app: flower
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command: ["celery", "-A", "celery_app.celery", "flower", "--port=5555"]
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.env.CELERY_BROKER_URL | quote }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.env.CELERY_RESULT_BACKEND | quote }}
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_USER
              value: "flask_user"
            - name: DB_PASSWORD
              value: "flask_password"
            - name: DB_NAME
              value: "flask_app"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 30
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
